services:
  knock-knock:
    image: ghcr.io/haruulzangi/knock-knock:latest
    read_only: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M
    restart: unless-stopped
    ports:
      - 8022:2222
    environment:
      - FLAG=HZ2025{kn000ck_$1_kn000ck_s0mething_h@pp3ns_in_ssh_$2_3v3ry_day}
